### ISSUE TITLE
Unable to run locally node v18.13.0

### ISSUE THREAD

**Issue by antonioortegajr** [smartdown/viewer#37]
Following the readme instruction the viewer would not run locally using v18.13.0

**Comment by DoctorBud** [comment]
Thanks for the data, @antonioortegajr ... I believe I have fixed the issue with a recent [PR](https://github.com/smartdown/viewer/pull/38). There are definitely issues with the README.md with respect to doing development on the `viewer` app, but `npm run dev` should work correctly in Node v16 AND v18.

FWIW, I'm currently prioritizing my work on the `viewer`'s replacement, which is a Quasar/VueJS app currently at [GitHub for smartdown-quasar](https://github.com/DoctorBud/smartdown-quasar/) and is demoable at [https://doctorbud.com/smartdown-quasar/](https://doctorbud.com/smartdown-quasar/). I intend to soon migrate that repository to the [smartdown](https://github.com/smartdown/) GitHub organization.

**Comment by antonioortegajr** [comment]
related PR https://github.com/smartdown/viewer/pull/38

**Comment by antonioortegajr** [comment]
Woking in node 18.13.0

Cloned repo npm i and dist directory built and runs as expected. 🚀
